### ISSUE TITLE
How to test the trained paragraph selector model?

### ISSUE THREAD

**Issue by gavenswang** [thunlp/OpenQA#2]
Hi，Thanks for your work！ I have trained a paragraph reader and paragraph selector model. Now I want to test my data with this model and select the paragraphs related to the question. How should I test?

**Comment by Mrlyk423** [comment]
Hi, just use the code "validate_unofficial_with_doc(args, test_loader_with_doc, model, stats, test_exs_with_doc, test_docs, 'test')" in main.py for testing. And you should format your data as the test.json and test.txt as my style.
