### ISSUE TITLE
A interactive demo ?

### ISSUE THREAD

**Issue by ElieAzeraf** [thunlp/OpenQA#3]
Hi !

Nice project, very interresting.
Do you have an interactive mode ? 
Like DrQA and its pre-trained model.

Otherwise, after training the model, how can I use this algorithm ?

Thanks a lot

**Comment by Mrlyk423** [comment]
Hi, we do not have a split testing code yet. Just use the code "validate_unofficial_with_doc(args, test_loader_with_doc, model, stats, test_exs_with_doc, test_docs, 'test')" in main.py for testing. And you should format your data as the test.json and test.txt as my style.

Later we will add  a split testing code for easier testing.

**Comment by ElieAzeraf** [comment]
Thanks a lot !
Very nice job !

**Comment by Arjunsankarlal** [comment]
I know it been long since this issue was closed, yet it might help other people who look into it.

> from src.reader.predictor import Predictor
predictor = Predictor(model='path_to_your_model')
output = predictor.predict('Document_text','Query')
print(output)

This will give you out the span along with it's score.
