### ISSUE TITLE
代码中的一些小问题

### ISSUE THREAD

**Issue by yumath** [thunlp/OpenQA#5]
首先，非常感谢您的这个工作，让我这个QA爱好者有一个向您学习的机会，看到您昨天还修改了代码，十分感谢。
但是我在运行您的开源代码时，还是遇到了以下一些小问题，还烦请指正：

· 在main.py的762行regex.split()是否应改成re.split()
· 在main.py的659行的两个参数train_exs和dev_exs是否应改为train_exs_with_doc以及dev_exs_with_doc
· src/__init__.py里还是import了pipelines，虽然已经删除了
· 在reader/model.py中的571行，调用了pipelines的PROCESS_CANDS，这里该如何处理

再次感谢！

**Comment by Mrlyk423** [comment]
感谢您的关注，我之后会将所有无关代码删去。
1. main.py的762行：这两者应该等效。
2. main.py的659行：由于我的代码里load pretrained model不需要新增词表，所以这里应该不会运行。
3. model.py中的571行：由于我的decode不需要candidates，这里不会运行到。

**Comment by yumath** [comment]
> 感谢您的关注，我之后会将所有无关代码删去。
> 
> 1. main.py的762行：这两者应该等效。
> 2. main.py的659行：由于我的代码里load pretrained model不需要新增词表，所以这里应该不会运行。
> 3. model.py中的571行：由于我的decode不需要candidates，这里不会运行到。

感谢您抽空解答我的疑惑，后面我还会持续关注您的工作，谢谢。
